# Generated by Django 4.2.1 on 2024-03-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0002_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=100)),
                ('workout_description', models.TextField()),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
