# Generated by Django 4.2.1 on 2024-03-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0003_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist_measurement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal', models.TextField()),
                ('workout_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitnessapp.workout')),
            ],
        ),
    ]
