# Generated by Django 4.2.1 on 2024-03-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0005_customerfeereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], max_length=50)),
                ('payment_date', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessapp.instructor')),
            ],
        ),
    ]
