# Generated by Django 4.2.1 on 2024-03-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0006_instructorsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='waist_measurement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight',
        ),
        migrations.CreateModel(
            name='CustomerFitness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist_measurement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goal', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessapp.customer')),
            ],
        ),
    ]
