# Generated by Django 4.2.1 on 2024-03-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0007_remove_customer_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='height',
        ),
    ]
