# Generated by Django 4.2.1 on 2024-03-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0009_workout_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessapp.instructor'),
        ),
    ]
