# Generated by Django 4.2.1 on 2024-03-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0010_alter_workout_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='instructor',
        ),
    ]
