# Generated by Django 4.2.1 on 2024-03-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0011_remove_workout_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitnessapp.instructor'),
        ),
    ]
