# Generated by Django 4.2.1 on 2024-03-29 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0012_workout_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfitness',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
