# Generated by Django 4.2.1 on 2024-03-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0013_customerfitness_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFitnessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise_duration', models.DurationField()),
                ('calories_burned', models.IntegerField()),
                ('water_consumed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnessapp.customer')),
            ],
        ),
    ]
